const keysShifted = [ 
  { symbol: '~', symbolRu: 'Ё', code: 'Backquote' },  
  { symbol: '!', symbolRu: '!', code: 'Digit1' },  
  { symbol: '"', symbolRu: '"', code: 'Digit2' }, 
  { symbol: '№', symbolRu: ';', code: 'Digit3' },
  { symbol: ';', symbolRu: 'ж', code: 'Digit4' },  
  { symbol: '%', symbolRu: '%', code: 'Digit5' },  
  { symbol: ':', symbolRu: 'щ', code: 'Digit6' },  
  { symbol: '?', symbolRu: ',', code: 'Digit7' },  
  { symbol: '*', symbolRu: '*', code: 'Digit8' },  
  { symbol: '(', symbolRu: '(', code: 'Digit9' },  
  { symbol: ')', symbolRu: ')', code: 'Digit0' },  
  { symbol: '_', symbolRu: '_', code: 'Minus' },  
  { symbol: '+', symbolRu: '+', code: 'Equal' },  
  { symbol: 'Backspace', symbolRu: 'Backspace', code: 'Backspace' },  
  { symbol: 'Tab', symbolRu: 'Tab', code: 'Tab' },  
  { symbol: 'Q', symbolRu: 'Й', code: 'KeyQ' },  
  { symbol: 'W', symbolRu: 'Ц', code: 'KeyW' },  
  { symbol: 'E', symbolRu: 'У', code: 'KeyE' },  
  { symbol: 'R', symbolRu: 'К', code: 'KeyR' },  
  { symbol: 'T', symbolRu: 'Е', code: 'KeyT' },  
  { symbol: 'Y', symbolRu: 'Н', code: 'KeyY' },  
  { symbol: 'U', symbolRu: 'Г', code: 'KeyU' },  
  { symbol: 'I', symbolRu: 'Ш', code: 'KeyI' },  
  { symbol: 'O', symbolRu: 'Щ', code: 'KeyO' },  
  { symbol: 'P', symbolRu: 'З', code: 'KeyP' },  
  { symbol: '{', symbolRu: 'Х', code: 'BracketLeft' },  
  { symbol: '}', symbolRu: 'Ъ', code: 'BracketRight' },  
  { symbol: '|', symbolRu: '/', code: 'Backslash' },  
  { symbol: 'Caps Lock', symbolRu: 'Caps Lock', code: 'CapsLock' },  
  { symbol: 'A', symbolRu: 'Ф', code: 'KeyA' },  
  { symbol: 'S', symbolRu: 'Ы', code: 'KeyS' },
  { symbol: 'D', symbolRu: 'В', code: 'KeyD' },
  { symbol: 'F', symbolRu: 'А', code: 'KeyF' },
  { symbol: 'G', symbolRu: 'П', code: 'KeyG' },
  { symbol: 'H', symbolRu: 'Р', code: 'KeyH' },
  { symbol: 'J', symbolRu: 'О', code: 'KeyJ' },
  { symbol: 'K', symbolRu: 'Л', code: 'KeyK' },
  { symbol: 'L', symbolRu: 'Д', code: 'KeyL' },
  { symbol: 'Ж', symbolRu: 'Ж', code: 'Semicolon' },
  { symbol: 'Э', symbolRu: 'Э', code: 'Quote' },
  { symbol: 'Enter', symbolRu: 'Enter', code: 'Enter' },
  { symbol: 'Shift', symbolRu: 'Shift', code: 'ShiftLeft' },
  { symbol: 'Z', symbolRu: 'Я', code: 'KeyZ' },
  { symbol: 'X', symbolRu: 'Ч', code: 'KeyX' },
  { symbol: 'C', symbolRu: 'С', code: 'KeyC' },
  { symbol: 'V', symbolRu: 'М', code: 'KeyV' },
  { symbol: 'B', symbolRu: 'И', code: 'KeyB' },
  { symbol: 'N', symbolRu: 'Т', code: 'KeyN' },
  { symbol: 'M', symbolRu: 'Ь', code: 'KeyM' },
  { symbol: '<', symbolRu: 'Б', code: 'Comma' },
  { symbol: '>', symbolRu: 'Ю', code: 'Period' },
  { symbol: '?', symbolRu: ',', code: 'Slash' },
  { symbol: '▲', symbolRu: '▲', code: 'ArrowUp',  isSpecial: true },
  { symbol: 'Shift', symbolRu: 'Shift', code: 'ShiftRight',  isSpecial: true },
  { symbol: 'Ctrl', symbolRu: 'Ctrl', code: 'ControlLeft',isSpecial: true },
  { symbol: 'Win', symbolRu: 'Win', code: 'MetaLeft',isSpecial: true },
  { symbol: 'Alt', symbolRu: 'Alt', code: 'AltLeft',isSpecial: true },
  { symbol: ' ', symbolRu: ' ', code: 'Space' },
  { symbol: 'Alt', symbolRu: 'Alt', code: 'AltRight',isSpecial: true },
  { symbol: 'Ctrl', symbolRu: 'Ctrl', code: 'ControlRight', isSpecial: true },
  { symbol: '◄', symbolRu: '◄', code: 'ArrowLeft', isSpecial: true },  
  { symbol: '▼', symbolRu: '▼', code: 'ArrowDown', isSpecial: true },
  { symbol: '►', symbolRu: '►', code: 'ArrowRight', isSpecial: true },
];