export const keys = [
[{ symbol: '`', symbolRu: 'ё', code: 'Backquote' },
{ symbol: '1', symbolRu: '1', code: 'Digit1' },
{ symbol: '2', symbolRu: '2', code: 'Digit2' },
{ symbol: '3', symbolRu: '3', code: 'Digit3' },
{ symbol: '4', symbolRu: '4', code: 'Digit4' },
{ symbol: '5', symbolRu: '5', code: 'Digit5' },
{ symbol: '6', symbolRu: '6', code: 'Digit6' },
{ symbol: '7', symbolRu: '7', code: 'Digit7' },
{ symbol: '8', symbolRu: '8', code: 'Digit8' },
{ symbol: '9', symbolRu: '9', code: 'Digit9' },
{ symbol: '0', symbolRu: '0', code: 'Digit0' },
{ symbol: '-', symbolRu: '-', code: 'Minus' },
{ symbol: '=', symbolRu: '=', code: 'Equal' },
{ symbol: 'Backspace', symbolRu: 'Backspace', code: 'Backspace', isSpecial: true }],
[{ symbol: 'Tab', symbolRu: 'Tab', code: 'Tab', isSpecial: true },
{ symbol: 'q', symbolRu: 'й', code: 'KeyQ' },
{ symbol: 'w', symbolRu: 'ц', code: 'KeyW' },
{ symbol: 'e', symbolRu: 'у', code: 'KeyE' },
{ symbol: 'r', symbolRu: 'к', code: 'KeyR' },
{ symbol: 't', symbolRu: 'е', code: 'KeyT' },
{ symbol: 'y', symbolRu: 'н', code: 'KeyY' },
{ symbol: 'u', symbolRu: 'г', code: 'KeyU' },
{ symbol: 'i', symbolRu: 'ш', code: 'KeyI' },
{ symbol: 'o', symbolRu: 'щ', code: 'KeyO' },
{ symbol: 'p', symbolRu: 'з', code: 'KeyP' },
{ symbol: '[', symbolRu: 'х', code: 'BracketLeft' },
{ symbol: ']', symbolRu: 'ъ', code: 'BracketRight' },
{ symbol: '\\', symbolRu: `\\`, code: 'Backslash' }],
[{ symbol: 'Del', symbolRu: 'Del', code: 'Delete', isSpecial: true },
{ symbol: 'CapsLk', symbolRu: 'CapsLk', code: 'CapsLock', isSpecial: true },
{ symbol: 'a', symbolRu: 'ф', code: 'KeyA' },
{ symbol: 's', symbolRu: 'ы', code: 'KeyS' },
{ symbol: 'd', symbolRu: 'в', code: 'KeyD' },
{ symbol: 'f', symbolRu: 'а', code: 'KeyF' },
{ symbol: 'g', symbolRu: 'п', code: 'KeyG' },
{ symbol: 'h', symbolRu: 'р', code: 'KeyH' },
{ symbol: 'j', symbolRu: 'о', code: 'KeyJ' },
{ symbol: 'k', symbolRu: 'л', code: 'KeyK' },
{ symbol: 'l', symbolRu: 'д', code: 'KeyL' },
{ symbol: ';', symbolRu: 'ж', code: 'Semicolon' },
{ symbol: `'`, symbolRu: 'э', code: 'Quote' },
{ symbol: 'Enter', symbolRu: 'Enter', code: 'Enter', isSpecial: true }],
[{ symbol: 'Shift', symbolRu: 'Shift', code: 'ShiftLeft', isSpecial: true },
{ symbol: 'z', symbolRu: 'я', code: 'KeyZ' },
{ symbol: 'x', symbolRu: 'ч', code: 'KeyX' },
{ symbol: 'c', symbolRu: 'с', code: 'KeyC' },
{ symbol: 'v', symbolRu: 'м', code: 'KeyV' },
{ symbol: 'b', symbolRu: 'и', code: 'KeyB' },
{ symbol: 'n', symbolRu: 'т', code: 'KeyN' },
{ symbol: 'm', symbolRu: 'ь', code: 'KeyM' },
{ symbol: ',', symbolRu: 'б', code: 'Comma' },
{ symbol: '.', symbolRu: 'ю', code: 'Period' },
{ symbol: '/', symbolRu: '.', code: 'Slash' },
{ symbol: '▲', symbolRu: '▲', code: 'ArrowUp',  isSpecial: true }],
[{ symbol: 'Shift', symbolRu: 'Shift', code: 'ShiftRight',  isSpecial: true },
{ symbol: 'Ctrl', symbolRu: 'Ctrl', code: 'ControlLeft',isSpecial: true },
{ symbol: 'Win', symbolRu: 'Win', code: 'MetaLeft',isSpecial: true },
{ symbol: 'Alt', symbolRu: 'Alt', code: 'AltLeft',isSpecial: true },
{ symbol: ' ', symbolRu: ' ', code: 'Space' },
{ symbol: 'Alt', symbolRu: 'Alt', code: 'AltRight',isSpecial: true },
{ symbol: 'Ctrl', symbolRu: 'Ctrl', code: 'ControlRight', isSpecial: true },
{ symbol: '◄', symbolRu: '◄', code: 'ArrowLeft', isSpecial: true },  
{ symbol: '▼', symbolRu: '▼', code: 'ArrowDown', isSpecial: true },
{ symbol: '►', symbolRu: '►', code: 'ArrowRight', isSpecial: true }]
];
